version: '3.8'
  
services:
  app:
    image: node:20.9
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install &&
      npm run dev -- --host"
    ports:
      - 3000:3000